apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: postgresql

          ports:
            - containerPort: 3306

          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc
            
            
